baseURL: 'https://eternalfire.github.io/test111/'
languageCode: 'cn'
title: '`\Â»ğŸ€ Â«/'
# theme: 'hyde'
theme: 'the-roots-home'

SectionPagesMenu: "main"

params:
  description: ". .. bin dev home tmp var etc usr ğŸ€…"

# relativeURLs: true

cleandestinationdir: true

# enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax: true
pygmentsCodeFences : true
pygmentsUseClasses: true
pygmentsStyle: vs
pygmentsOptions:
  linenos: true

# markup:
#   defaultMarkdownHandler: goldmark
