baseURL: 'https://eternalfire.github.io/test111/'
languageCode: 'cn'
title: '`\Â»ğŸ€ Â«/'
# theme: 'hyde'
theme: 'the-roots-home'

SectionPagesMenu: "main"

params:
  description: ". .. bin dev home tmp var etc usr ğŸ€…"

# relativeURLs: true

cleandestinationdir: true

# enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax: true
pygmentsCodeFences : true
pygmentsUseClasses: true
pygmentsStyle: vs
pygmentsOptions:
  linenos: true

# markup:
#   defaultMarkdownHandler: goldmark

# goldmark
# This is the default configuration:

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

